
// import "@assets/scss/bootstrap.scss";
// import "@assets/scss/app.scss";
// import "@assets/icons/font-icon.css";
// // import Head from "next/head";
// import { ReactNode } from "react";
// import {Metadata} from "next";
// import { Inter, Playfair_Display } from "next/font/google";
// import Providers from "@src/app/providers";

// const fontSans = Inter({
//   subsets: ["latin", "cyrillic"],
//   variable: "--font-sans",
//   display: "swap",
// });

// const fontSerif = Playfair_Display({
//   subsets: ["latin", "cyrillic"],
//   variable: "--font-serif",
//   display: "swap",
// });

// export function generateViewport(): Record<string, string | number> {
//   return {
//     width: "device-width",
//     initialScale: 1,
//     userScalable: "no",
//   };
// }

// export const metadata: Metadata = {
//   title: "Kalles",
//   description: "Generated by Kalles",
//   icons: {
//     icon: "/favicon.ico",
//   },
// };

// interface LayoutProps {
//   children: ReactNode;
// }

// export default function Layout({ children }: LayoutProps) {
//   return (
//     <html lang="en">
//     <body>
//     {/*<p>*/}
//     {/*  {JSON.stringify(fontSans, null, 2)}*/}
//     {/*</p>*/}
//     <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }


import "@assets/scss/bootstrap.scss";
import "@assets/scss/app.scss";
import "@assets/icons/font-icon.css";
// import Head from "next/head";
import { ReactNode } from "react";
import {Metadata} from "next";
import { Inter, Playfair_Display } from "next/font/google";
import Providers from "@src/app/providers";

const fontSans = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-sans",
  display: "swap",
});

const fontSerif = Playfair_Display({
  subsets: ["latin", "cyrillic"],
  variable: "--font-serif",
  display: "swap",
});

export function generateViewport(): Record<string, string | number> {
  return {
    width: "device-width",
    initialScale: 1,
    userScalable: "no",
  };
}

export const metadata: Metadata = {
  title: "Офисные двери",
  description: "Headless интернет-магазин межкомнатных дверей с комплектацией и заказом без онлайн-оплаты.",
  icons: {
    icon: "/favicon.ico",
  },
};

interface LayoutProps {
  children: ReactNode;
}

export default function Layout({ children }: LayoutProps) {
  return (
    <html lang="ru">
    <body>
    {/*<p>*/}
    {/*  {JSON.stringify(fontSans, null, 2)}*/}
    {/*</p>*/}
    <Providers>{children}</Providers>
      </body>
    </html>
  );
}
